### ISSUE TITLE
Problem z budowaniem aplikacji po checkoucie

### ISSUE THREAD

**Issue by MurawskiKamil** [MurawskiKamil/training-registry#18]
`Could not find module "@angular-devkit/build-angular" from "/home/kmurawski/work/training-registry/frontend/training-registry".
Error: Could not find module "@angular-devkit/build-angular" from "/home/kmurawski/work/training-registry/frontend/training-registry".
    at Object.resolve (/home/kmurawski/.nvm/versions/node/v8.11.3/lib/node_modules/@angular/cli/node_modules/@angular-devkit/core/node/resolve.js:141:11)
    at Observable.rxjs_1.Observable [as _subscribe] (/home/kmurawski/.nvm/versions/node/v8.11.3/lib/node_modules/@angular/cli/node_modules/@angular-devkit/architect/src/architect.js:132:40)
    at Observable._trySubscribe (/home/kmurawski/.nvm/versions/node/v8.11.3/lib/node_modules/@angular/cli/node_modules/rxjs/internal/Observable.js:43:25)
    at Observable.subscribe (/home/kmurawski/.nvm/versions/node/v8.11.3/lib/node_modules/@angular/cli/node_modules/rxjs/internal/Observable.js:29:22)
    at DoOperator.call (/home/kmurawski/.nvm/versions/node/v8.11.3/lib/node_modules/@angular/cli/node_modules/rxjs/internal/operators/tap.js:29:23)
    at Observable.subscribe (/home/kmurawski/.nvm/versions/node/v8.11.3/lib/node_modules/@angular/cli/node_modules/rxjs/internal/Observable.js:24:22)
    at /home/kmurawski/.nvm/versions/node/v8.11.3/lib/node_modules/@angular/cli/node_modules/rxjs/internal/util/subscribeTo.js:22:31
    at Object.subscribeToResult (/home/kmurawski/.nvm/versions/node/v8.11.3/lib/node_modules/@angular/cli/node_modules/rxjs/internal/util/subscribeToResult.js:7:45)
    at MergeMapSubscriber._innerSub (/home/kmurawski/.nvm/versions/node/v8.11.3/lib/node_modules/@angular/cli/node_modules/rxjs/internal/operators/mergeMap.js:75:38)
    at MergeMapSubscriber._tryNext (/home/kmurawski/.nvm/versions/node/v8.11.3/lib/node_modules/@angular/cli/node_modules/rxjs/internal/operators/mergeMap.js:72:14)
`

**Comment by MurawskiKamil** [comment]
Usuwamy node_modules z .gitignore.

Instalujemy build-angular:
npm install --save-dev @angular-devkit/build-angular

**Comment by MurawskiKamil** [comment]
Zrobione.
